reloader:
  deployment:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "Addon-Services"
              operator: In
              values:
              - "true"

    pod:
      annotations:
        co.elastic.logs/enabled: "true"

  serviceMonitor:
    enabled: ${enable_service_monitor}
