installCRDs: true

## Node affinity for particular node in which labels key is "Addon-Services" and value is "true"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Addon-Services"
          operator: In
          values:
          - "true"

webhook:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "Addon-Services"
            operator: In
            values:
            - "true"

  podAnnotations:
    co.elastic.logs/enabled: "true"

cainjector:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "Addon-Services"
            operator: In
            values:
            - "true"

  podAnnotations:
    co.elastic.logs/enabled: "true"
prometheus:
  enabled: ${enable_service_monitor}
  servicemonitor:
    enabled: ${enable_service_monitor}
    labels:
      release: "prometheus-operator"
